### ISSUE TITLE
Binary Tree Level order Traversal

### ISSUE THREAD

**Issue by sachin235** [sachin235/HacktoberFest101#210]
Add C++ code for Binary Tree Level Order Traversal.

**Comment by sachin235** [comment]
C++ code added with the PR #203

**Comment by sachin235** [comment]
Code required in other programming languages as well.

**Comment by Nripen-13** [comment]
Sir please assign this problem to me

**Comment by Dishu099** [comment]
Hey @sachin235  can I add my code to this issue

**Comment by sachin235** [comment]
@Nripen-13 @Dishu099 
C++ code is already added for this. Feel free to contribute and raise PR for code in any other language of your choice.

**Comment by Dishu099** [comment]
okay can you  assign this so I can add code in other lang

**Comment by sachin235** [comment]
Sure @Dishu099 go ahead, assigned!

**Comment by Dishu099** [comment]
Can you checkout my PR I have added my code in c++ @sachin235

**Comment by sachin235** [comment]
Closed with #203
