### ISSUE TITLE
Flatten Binary Tree code

### ISSUE THREAD

**Issue by sachin235** [sachin235/HacktoberFest101#211]
Add code for Flatten Binary Tree in different languauges.

**Comment by Ris-code** [comment]
Hey, can you assign me this

**Comment by idrismusa4** [comment]
@sachin235 How many languages precisely

**Comment by sachin235** [comment]
@Ris-code @idrismusa4 
The C++ code for this problem is already added. Feel free to contribute in any one of the other languages(Java/ Python, etc) and raise PR for the same.

**Comment by Ris-code** [comment]
I can do it in python, please assign me this

**Comment by sachin235** [comment]
Resolved with #205 & #222
