### ISSUE TITLE
Diagonal sum in a Binary Tree

### ISSUE THREAD

**Issue by sachin235** [sachin235/HacktoberFest101#212]
Add code in your favorite programming language.

**Comment by Ris-code** [comment]
Hey,can you assign me this

**Comment by idrismusa4** [comment]
Please assign this issue to me? @sachin235

**Comment by sachin235** [comment]
@Ris-code @idrismusa4 
Please specify the programming language in which you would like to contribute as well. The C++ code for this problem is already added. Feel free to contribute in any one of the other languages(Java/ Python, etc) and raise PR for the same.

**Comment by Ris-code** [comment]
Ya, I could do it in python

**Comment by sachin235** [comment]
Sure @Ris-code , assigned

**Comment by idrismusa4** [comment]
Assign me please @sachin235

**Comment by sachin235** [comment]
Resolved with #207, #222 & #226
