### ISSUE TITLE
Bottom View of Binary Tree

### ISSUE THREAD

**Issue by sachin235** [sachin235/HacktoberFest101#213]
Add code in programming language of your choice.

**Comment by aman6969** [comment]
please assign this to me @sachin235

**Comment by sachin235** [comment]
The C++ code is already added with #208 
@aman6969 would you like to pick it up for any other language?

**Comment by aman6969** [comment]
I have created a fork and added my code in java folder i have coded in java lang. since, you said cpp is already merged please merge by PR @sachin235

**Comment by sachin235** [comment]
@aman6969 I don't see your PR yet? Please raise the PR, so that I can review and merge it

**Comment by aman6969** [comment]
[29e9b24](https://github.com/aman6969/bottom-view-of-binary-tree/commit/29e9b243d3e6e5608a13bfb904fe7849dab7e341) please check  your fork @sachin235

**Comment by sachin235** [comment]
@aman6969 you had to create a PR after making changes in your fork like this #249 
To learn about how to create PR, you can refer resources mentioned in Readme of this repo.

**Comment by sachin235** [comment]
Resolved with #208 & #249

**Comment by aman6969** [comment]
ok thank you @sachin235
