### ISSUE TITLE
Bucket Sort

### ISSUE THREAD

**Issue by sachin235** [sachin235/HacktoberFest101#220]
Add code for Bucket Sort algorithm in the language of your choice.

**Comment by rutuja1121** [comment]
Can I work on this issue?

**Comment by harshpailkar** [comment]
Can you pls assign me this @sachin235 ?

**Comment by sachin235** [comment]
@rutuja1121 @harshpailkar 
Bucket Sort algorithm for C++ has already been added. Feel free to add codes for Python & Java, and raise PR.

**Comment by harshpailkar** [comment]
I've added the code for Bucket Sort in the python folder. Please merge my PR

**Comment by sachin235** [comment]
Resolved with #235, #246 & #248
