### ISSUE TITLE
Update the folder structure

### ISSUE THREAD

**Issue by sachin235** [sachin235/HacktoberFest101#241]
- Move the code files to the correct folders
- Update file names as per the correct convention
- Delete redundant files

**Comment by harshpatel2212** [comment]
@sachin235 I would like to work on this. Can you please assign this to me?

**Comment by harshpatel2212** [comment]
#243 You may check it...Please add hacktoberfest-accepted label to this as well. Thank You!

**Comment by sachin235** [comment]
Resolved with #234, #240, #242 & #243
