### ISSUE TITLE
Java Programming Questions

### ISSUE THREAD

**Issue by riya0522** [sachin235/HacktoberFest101#272]
@sachin235,

I would like to make Java code contributions to these problems under Hacktober fest. Can you please assign these to me?

1. **Count Primes** : Given an integer n, return the number of prime numbers that are strictly less than n.
2. **Triangle** : Given a triangle array, return the minimum path sum from top to bottom. For each step, you may move to an adjacent number of the row below. More formally, if you are on index i on the current row, you may move to either index i or index i + 1 on the next row.
3. **Furthest Building You Can Reach** : You are given an integer array heights representing the heights of buildings, some bricks, and some ladders.You start your journey from building 0 and move to the next building by possibly using bricks or ladders.While moving from building i to building i+1 (0-indexed),If the current building's height is greater than or equal to the next building's height, you do not need a ladder or bricks.If the current building's height is less than the next building's height, you can either use one ladder or (h[i+1] - h[i]) bricks.Return the furthest building index (0-indexed) you can reach if you use the given ladders and bricks optimally.
4. **Deepest Leaves Sum** : Given the root of a binary tree, return the sum of values of its deepest leaves.

**Comment by sachin235** [comment]
Hi @riya0522 sure, go ahead.
This looks good!

**Comment by sachin235** [comment]
Resolved with #274 - #278
